/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.foo.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Foo service. Represents a row in the &quot;Foo_Foo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.foo.model.impl.FooModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.foo.model.impl.FooImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Foo
 * @see com.liferay.foo.model.impl.FooImpl
 * @see com.liferay.foo.model.impl.FooModelImpl
 * @generated
 */
@ProviderType
public interface FooModel extends BaseModel<Foo>, GroupedModel, ShardedModel,
	StagedAuditedModel, TrashedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a foo model instance should use the {@link Foo} interface instead.
	 */

	/**
	 * Returns the primary key of this foo.
	 *
	 * @return the primary key of this foo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this foo.
	 *
	 * @param primaryKey the primary key of this foo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this foo.
	 *
	 * @return the uuid of this foo
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this foo.
	 *
	 * @param uuid the uuid of this foo
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the foo ID of this foo.
	 *
	 * @return the foo ID of this foo
	 */
	public long getFooId();

	/**
	 * Sets the foo ID of this foo.
	 *
	 * @param fooId the foo ID of this foo
	 */
	public void setFooId(long fooId);

	/**
	 * Returns the title of this foo.
	 *
	 * @return the title of this foo
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this foo.
	 *
	 * @param title the title of this foo
	 */
	public void setTitle(String title);

	/**
	 * Returns the foo boolean stat of this foo.
	 *
	 * @return the foo boolean stat of this foo
	 */
	public boolean getFooBooleanStat();

	/**
	 * Returns <code>true</code> if this foo is foo boolean stat.
	 *
	 * @return <code>true</code> if this foo is foo boolean stat; <code>false</code> otherwise
	 */
	public boolean isFooBooleanStat();

	/**
	 * Sets whether this foo is foo boolean stat.
	 *
	 * @param fooBooleanStat the foo boolean stat of this foo
	 */
	public void setFooBooleanStat(boolean fooBooleanStat);

	/**
	 * Returns the foo date time of this foo.
	 *
	 * @return the foo date time of this foo
	 */
	public Date getFooDateTime();

	/**
	 * Sets the foo date time of this foo.
	 *
	 * @param fooDateTime the foo date time of this foo
	 */
	public void setFooDateTime(Date fooDateTime);

	/**
	 * Returns the foo document library of this foo.
	 *
	 * @return the foo document library of this foo
	 */
	@AutoEscape
	public String getFooDocumentLibrary();

	/**
	 * Sets the foo document library of this foo.
	 *
	 * @param fooDocumentLibrary the foo document library of this foo
	 */
	public void setFooDocumentLibrary(String fooDocumentLibrary);

	/**
	 * Returns the foo double of this foo.
	 *
	 * @return the foo double of this foo
	 */
	public double getFooDouble();

	/**
	 * Sets the foo double of this foo.
	 *
	 * @param fooDouble the foo double of this foo
	 */
	public void setFooDouble(double fooDouble);

	/**
	 * Returns the foo integer of this foo.
	 *
	 * @return the foo integer of this foo
	 */
	public int getFooInteger();

	/**
	 * Sets the foo integer of this foo.
	 *
	 * @param fooInteger the foo integer of this foo
	 */
	public void setFooInteger(int fooInteger);

	/**
	 * Returns the foo rich text of this foo.
	 *
	 * @return the foo rich text of this foo
	 */
	@AutoEscape
	public String getFooRichText();

	/**
	 * Sets the foo rich text of this foo.
	 *
	 * @param fooRichText the foo rich text of this foo
	 */
	public void setFooRichText(String fooRichText);

	/**
	 * Returns the foo text of this foo.
	 *
	 * @return the foo text of this foo
	 */
	@AutoEscape
	public String getFooText();

	/**
	 * Sets the foo text of this foo.
	 *
	 * @param fooText the foo text of this foo
	 */
	public void setFooText(String fooText);

	/**
	 * Returns the group ID of this foo.
	 *
	 * @return the group ID of this foo
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this foo.
	 *
	 * @param groupId the group ID of this foo
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this foo.
	 *
	 * @return the company ID of this foo
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this foo.
	 *
	 * @param companyId the company ID of this foo
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this foo.
	 *
	 * @return the user ID of this foo
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this foo.
	 *
	 * @param userId the user ID of this foo
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this foo.
	 *
	 * @return the user uuid of this foo
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this foo.
	 *
	 * @param userUuid the user uuid of this foo
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this foo.
	 *
	 * @return the user name of this foo
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this foo.
	 *
	 * @param userName the user name of this foo
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this foo.
	 *
	 * @return the create date of this foo
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this foo.
	 *
	 * @param createDate the create date of this foo
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this foo.
	 *
	 * @return the modified date of this foo
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this foo.
	 *
	 * @param modifiedDate the modified date of this foo
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the url title of this foo.
	 *
	 * @return the url title of this foo
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this foo.
	 *
	 * @param urlTitle the url title of this foo
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the foo title name of this foo.
	 *
	 * @return the foo title name of this foo
	 */
	@AutoEscape
	public String getFooTitleName();

	/**
	 * Sets the foo title name of this foo.
	 *
	 * @param fooTitleName the foo title name of this foo
	 */
	public void setFooTitleName(String fooTitleName);

	/**
	 * Returns the foo summary name of this foo.
	 *
	 * @return the foo summary name of this foo
	 */
	@AutoEscape
	public String getFooSummaryName();

	/**
	 * Sets the foo summary name of this foo.
	 *
	 * @param fooSummaryName the foo summary name of this foo
	 */
	public void setFooSummaryName(String fooSummaryName);

	/**
	 * Returns the status of this foo.
	 *
	 * @return the status of this foo
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this foo.
	 *
	 * @param status the status of this foo
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this foo.
	 *
	 * @return the status by user ID of this foo
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this foo.
	 *
	 * @param statusByUserId the status by user ID of this foo
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this foo.
	 *
	 * @return the status by user uuid of this foo
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this foo.
	 *
	 * @param statusByUserUuid the status by user uuid of this foo
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this foo.
	 *
	 * @return the status by user name of this foo
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this foo.
	 *
	 * @param statusByUserName the status by user name of this foo
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this foo.
	 *
	 * @return the status date of this foo
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this foo.
	 *
	 * @param statusDate the status date of this foo
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the trash entry created when this foo was moved to the Recycle Bin. The trash entry may belong to one of the ancestors of this foo.
	 *
	 * @return the trash entry created when this foo was moved to the Recycle Bin
	 */
	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException;

	/**
	 * Returns the class primary key of the trash entry for this foo.
	 *
	 * @return the class primary key of the trash entry for this foo
	 */
	@Override
	public long getTrashEntryClassPK();

	/**
	 * Returns the trash handler for this foo.
	 *
	 * @return the trash handler for this foo
	 * @deprecated As of 7.0.0, with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler();

	/**
	 * Returns <code>true</code> if this foo is in the Recycle Bin.
	 *
	 * @return <code>true</code> if this foo is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrash();

	/**
	 * Returns <code>true</code> if the parent of this foo is in the Recycle Bin.
	 *
	 * @return <code>true</code> if the parent of this foo is in the Recycle Bin; <code>false</code> otherwise
	 */
	@Override
	public boolean isInTrashContainer();

	@Override
	public boolean isInTrashExplicitly();

	@Override
	public boolean isInTrashImplicitly();

	/**
	 * Returns <code>true</code> if this foo is approved.
	 *
	 * @return <code>true</code> if this foo is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this foo is denied.
	 *
	 * @return <code>true</code> if this foo is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this foo is a draft.
	 *
	 * @return <code>true</code> if this foo is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this foo is expired.
	 *
	 * @return <code>true</code> if this foo is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this foo is inactive.
	 *
	 * @return <code>true</code> if this foo is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this foo is incomplete.
	 *
	 * @return <code>true</code> if this foo is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this foo is pending.
	 *
	 * @return <code>true</code> if this foo is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this foo is scheduled.
	 *
	 * @return <code>true</code> if this foo is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Foo foo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Foo> toCacheModel();

	@Override
	public Foo toEscapedModel();

	@Override
	public Foo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}